//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskRyabykin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestTaskRyabykin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields with long names should be shortened.
        /// </summary>
        internal static string FieldLengthAnalyzerDescription {
            get {
                return ResourceManager.GetString("FieldLengthAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; name is too long.
        /// </summary>
        internal static string FieldLengthAnalyzerFormat {
            get {
                return ResourceManager.GetString("FieldLengthAnalyzerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name is too long.
        /// </summary>
        internal static string FieldLengthAnalyzerTitle {
            get {
                return ResourceManager.GetString("FieldLengthAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variables with long names should be shortened.
        /// </summary>
        internal static string LocalVariableLengthAnalyzerDescription {
            get {
                return ResourceManager.GetString("LocalVariableLengthAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; name is too long.
        /// </summary>
        internal static string LocalVariableLengthAnalyzerFormat {
            get {
                return ResourceManager.GetString("LocalVariableLengthAnalyzerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name is too long.
        /// </summary>
        internal static string LocalVariableLengthAnalyzerTitle {
            get {
                return ResourceManager.GetString("LocalVariableLengthAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods with long names should be shortened.
        /// </summary>
        internal static string MethodLengthAnalyzerDescription {
            get {
                return ResourceManager.GetString("MethodLengthAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; name is too long.
        /// </summary>
        internal static string MethodLengthAnalyzerFormat {
            get {
                return ResourceManager.GetString("MethodLengthAnalyzerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name is too long.
        /// </summary>
        internal static string MethodLengthAnalyzerTitle {
            get {
                return ResourceManager.GetString("MethodLengthAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties with long names should be shortened.
        /// </summary>
        internal static string PropertyLengthAnalyzerDescription {
            get {
                return ResourceManager.GetString("PropertyLengthAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; name is too long.
        /// </summary>
        internal static string PropertyLengthAnalyzerFormat {
            get {
                return ResourceManager.GetString("PropertyLengthAnalyzerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name is too long.
        /// </summary>
        internal static string PropertyLengthAnalyzerTitle {
            get {
                return ResourceManager.GetString("PropertyLengthAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types with long names should be shortened.
        /// </summary>
        internal static string TypeLengthAnalyzerDescription {
            get {
                return ResourceManager.GetString("TypeLengthAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; name is too long.
        /// </summary>
        internal static string TypeLengthAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("TypeLengthAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name is too long.
        /// </summary>
        internal static string TypeLengthAnalyzerTitle {
            get {
                return ResourceManager.GetString("TypeLengthAnalyzerTitle", resourceCulture);
            }
        }
    }
}
